//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Books
    {
        public long ID { get; set; }
        [Display(Name = "Автор")]
        public Nullable<long> Author { get; set; }
        [Display(Name = "Название")]
        public string Name { get; set; }
        [Display(Name = "Год издания")]
        public string DataPrint { get; set; }
        [Display(Name = "Тип обложки")]
        public Nullable<int> CoverType { get; set; }
        [Display(Name = "Возрастное ограничение")]
        public Nullable<int> AgeCategory { get; set; }
        [Display(Name = "Жанр")]
        public Nullable<int> Genre { get; set; }
    
        public virtual AgeCategory AgeCategory1 { get; set; }
        public virtual Authors Authors { get; set; }
        public virtual CoverTypes CoverTypes { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
